backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'article'
    label: Article
    folder: 'content/articles'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Path', name: 'path', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: "Title", name: 'title', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'string' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Type', name: 'type', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
